---
- name: Include OS specific tasks
  include_tasks:
    file: "{{ role_path }}/tasks/{{ ansible_distribution | lower }}.yml"

- name: Install docker
  package:
    name: "{{ generic_docker_package }}"
    state: present

- name: Create /etc/docker/
  file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: Start docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Create daemon.json
  copy:
    content: "{{ generic_docker_daemon_json | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: '0640'
  notify: restart docker
  when: generic_docker_daemon_json.keys() | length > 0

- name: Install pip
  package:
    name: python3-pip
    state: present

- name: Install docker python module
  pip:
    name: "{{ generic_docker_pip_modules }}"
    executable: pip3
  when: generic_docker_pip_modules is defined and ( generic_docker_pip_modules |length>0 )

- name: Include docker compose tasks
  include_tasks:
    file: docker-compose.yml
    apply:
      tags: docker-compose
  tags: docker-compose
  when: generic_docker_install_compose